apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-share-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-share
  template:
    metadata:
      labels:
        app: file-share
    spec:
      containers:
        - name: app
          image: davidjay2111/real-time-file-sharing:build-13
          ports:
            - containerPort: 3000
